spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://qqmysql:3306/ticketbooking?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: Didiren82325
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Ticketbooking
#  session:
#    store-type: redis
#  redis:
#    host: qq.nobler.me
#    port: 6379
#    password: Didiren82325
#    database: 2
server:
  port: 10101
eureka:
  client:
    service-url:
      defaultZone: http://peer1:30301/eureka,http://peer2:30302/eureka
#eureka:
#  client:
#    service-url: http://localhost:1111/eureka/


#---
#spring:
#  profiles: server1
#server:
#  port: 8001
#
#---
#spring:
#  profiles: server2
#server:
#  port: 8002